const data =  {
    products:[
        {
        _id: '1',
        name:'Indian Tabla',
        category:'Hindustani',
        image:'https://www.dressinn.com/f/13687/136872891/wrangler-logo-hoodie.jpg',
        price: 2000,
        brand: 'Givson',
        rating: "5",
        countInstock : 0, 
    }, 
    {
        _id: '2',
        name:'Indian Flute',
        category:'Hindustani',
        image:'https://www.dressinn.com/f/13687/136872891/wrangler-logo-hoodie.jpg',
        price: 2000,
        brand: 'Givson',
        rating: "5",
        countInstock : 6, 
    }, 
    {
        _id: '3',
        name:'Piano',
        category:'Western',
        image:'https://www.dressinn.com/f/13687/136872891/wrangler-logo-hoodie.jpg',
        price: 2000,
        brand: 'Givson',
        rating: "5",
        countInstock : 6, 
    }, 
    {
        _id: '4',
        name:'Harmonica',
        category:'Western',
        image:'https://www.dressinn.com/f/13687/136872891/wrangler-logo-hoodie.jpg',
        price: 2000,
        brand: 'Givson',
        rating: "5",
        countInstock : 6, 
    }, 
    {
        _id: '5',
        name:'Bass Guitar',
        category:'Guitars',
        image:'https://www.dressinn.com/f/13687/136872891/wrangler-logo-hoodie.jpg',
        price: 2000,
        brand: 'Givson',
        rating: "5",
        countInstock : 6, 
    }, 
    {
        _id: '6',
        name:'Electric Guitar',
        category:'Guitars',
        image:'https://www.dressinn.com/f/13687/136872891/wrangler-logo-hoodie.jpg',
        price: 2000,
        brand: 'Givson',
        rating: "5",
        countInstock : 6, 
    }, 
]
}

module.exports = data;